name: Gold ETL

on:
    workflow_dispatch
permissions:
      id-token: write
      contents: read
jobs:
    
    get_results:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.11
              uses: actions/setup-python@v2
              with:
                  python-version: 3.11
            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v1.7.0
              with:
                role-to-assume: arn:aws:iam::105144480348:role/github-actions
                role-session-name: GitHub_to_AWS_via_FederatedOIDC
                aws-region: il-central-1
                audience: sts.amazonaws.com
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
              continue-on-error: false

            - name: Get Latest Results
              run: |
                  python scripts/get_results.py
              continue-on-error: false

            - name: Run Gold ETL
              run: |
                  python scripts/gold_etl.py
