name: Production Deployment

on:
    workflow_dispatch
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.11
              uses: actions/setup-python@v2
              with:
                  python-version: 3.11
            - name: Run deploy script
              run: |
                  ./deploy_api.sh
